#!/usr/bin/env bash

#Variaveis 
data_criacao=$( date +'%d/%m/%Y')
cabecalho="#!/usr/bin/env bash


#----------------| Script-$1 |-------------------
#
# Nome: $1
# Descricao:
# Autor: Jonathan Nas. Dutra <jonatthan.dutra@gmail.com>
# Data:  $data_criacao
# Versão: 00.1
# Licença: GNU/GPL v3.0 
# OBS: Arquivo criado com base nos videos do Blau : https://www.youtube.com/@debxp
#----------------------------------------------------
# Uso:
#
#----------------------------------------------------"
# Teste

[[ $# -ne 1 ]] && echo " Informe apenas um nome!!" && exit 1
[[ -f $1.sh ]] && echo "Esse aquivo já existe" && exit 2

# Criação do aruivo
echo "$cabecalho">$1.sh

chmod uo+x $1.sh
nano $1.sh
exit 0
