#!/usr/bin/env bash

# Nome: Teste_B
# Descricao: Verificar se um comando é interno ou externo
# Autor:  Jonathan Nasc. Dutra
# OBS: Arquivo criado com base nos videos do Blau : https://www.youtube.com/@debxp
# Versao: 0001

